
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * The PrivateSession class represents a private session between two users. It
 * contains the session ID, the usernames of the
 * two users involved, an ObjectOutputStream to write to the other user, a list
 * of voice notes received, and GUI components
 * to display the session.
 */
public class PrivateSession extends javax.swing.JFrame {

	Integer sessionId;
	String username;
	ObjectOutputStream out;
	String invitee;
	ArrayList<String> vnReceived;
	boolean inCall = false;

	/**
	 * Creates a new PrivateSession object with the given session ID, username,
	 * ObjectOutputStream, invitee, and list of
	 * received voice notes.
	 *
	 * @param sessionId  the session ID
	 * @param username   the username of the user
	 * @param out        the ObjectOutputStream to write to the other user
	 * @param invitee    the username of the user being invited to the session
	 * @param vnReceived the list of voice notes received during the session
	 */
	public PrivateSession(Integer sessionId, String username, ObjectOutputStream out, String invitee,
			ArrayList<String> vnReceived) {
		initComponents();
		scaleImage(jLabel1, "images/private-session.png");
		this.sessionId = sessionId;
		this.username = username;
		this.out = out;
		this.invitee = invitee;
		this.vnReceived = vnReceived;
		jLabel7.setText(invitee);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel9 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel3 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel9.setBackground(new java.awt.Color(33, 36, 43));

		jPanel1.setBackground(new java.awt.Color(45, 49, 58));

		jLabel1.setText("jLabel1");

		jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Private Session");
		jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(21, 21, 21)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										56,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										604, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												56, Short.MAX_VALUE)
										.addComponent(jLabel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addContainerGap()));

		jPanel2.setBackground(new java.awt.Color(45, 49, 58));

		jScrollPane1.setBorder(null);

		jTextArea1.setBackground(new java.awt.Color(45, 49, 58));
		jTextArea1.setColumns(20);
		jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea1.setRows(5);
		jTextArea1.setFocusable(false);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1)
								.addContainerGap()));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										201, Short.MAX_VALUE)
								.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(45, 49, 58));

		jTextField1.setBackground(new java.awt.Color(45, 49, 58));
		jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jTextField1.setForeground(new java.awt.Color(255, 255, 255));
		jTextField1.setText("Type your message here...");
		jTextField1.setBorder(null);
		jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextField1FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField1FocusLost(evt);
			}
		});
		jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField1MouseClicked(evt);
			}
		});
		jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField1KeyPressed(evt);
			}
		});

		jPanel5.setBackground(new java.awt.Color(45, 49, 58));
		jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 76, 223), 4));

		jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(137, 76, 223));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("Send");
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel4MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel4MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel4MouseExited(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel4,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										51, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel4,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										35, Short.MAX_VALUE)
								.addContainerGap()));

		jPanel6.setBackground(new java.awt.Color(45, 49, 58));
		jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 76, 223), 4));

		jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(137, 76, 223));
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("VN");
		jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel5MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel5MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel5MouseExited(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel5,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										38, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel5,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addContainerGap(15, Short.MAX_VALUE)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										450,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel5,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel6,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel3Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel5,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jPanel6,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jTextField1,
												javax.swing.GroupLayout.Alignment.TRAILING))
								.addContainerGap()));

		jPanel4.setBackground(new java.awt.Color(33, 36, 43));
		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 76, 223), 4));

		jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(137, 76, 223));
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setText("Disconnect");
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel6MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel6MouseExited(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel6,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel6,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										33, Short.MAX_VALUE)
								.addContainerGap()));

		jPanel7.setBackground(new java.awt.Color(137, 76, 223));

		jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setText("Username");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel7,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										229, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel7Layout.setVerticalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel7,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addGap(40, 40, 40)
								.addGroup(jPanel9Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel9Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														false)
												.addComponent(jPanel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jPanel3,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jPanel4,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
										.addComponent(jPanel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel9Layout.setVerticalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(41, 41, 41)
								.addComponent(jPanel7,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(38, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * This method is called when the user presses a key in the jTextField1 text
	 * field.
	 * If the key is the Enter key, it calls the send button's code.
	 * 
	 * @param evt the KeyEvent that triggered the method
	 */
	private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyPressed

		// call the send button's code on enter key
		if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
			jLabel4MouseClicked(null);
		}

	}// GEN-LAST:event_jTextField1KeyPressed

	/**
	 * This method is called when the user clicks on the "disconnect" label.
	 * It sends a packet to the server to disconnect the user from the session.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseClicked

		// use invite packet for isPrivate attr
		Packet packet = new Packet("disconnectSession", true, sessionId, null);

		try {
			out.writeObject(packet);
		} catch (IOException e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_jLabel6MouseClicked

	/**
	 * This method is called when the user hovers the mouse over the "send message"
	 * label.
	 * It changes the foreground and background colors of the label and panel.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MouseEntered
		// TODO add your handling code here:
		jLabel4.setForeground(jPanel5.getBackground());
		jPanel5.setBackground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel4MouseEntered

	/**
	 * This method is called when the user moves the mouse out of the "send message"
	 * label.
	 * It changes the foreground and background colors of the label and panel.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MouseExited
		// TODO add your handling code here:
		jPanel5.setBackground(jLabel4.getForeground());
		jLabel4.setForeground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel4MouseExited

	/**
	 * This method is called when the user hovers the mouse over the "send voice
	 * note" label.
	 * It changes the foreground and background colors of the label and panel.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseEntered
		// TODO add your handling code here:
		jLabel5.setForeground(jPanel6.getBackground());
		jPanel6.setBackground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel5MouseEntered

	/**
	 * This method is called when the user moves the mouse out of the "send voice
	 * note" label.
	 * It changes the foreground and background colors of the label and panel.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseExited
		// TODO add your handling code here:
		jPanel6.setBackground(jLabel5.getForeground());
		jLabel5.setForeground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel5MouseExited

	/**
	 * This method is called when the user hovers the mouse over the "disconnect"
	 * label.
	 * It changes the foreground and background colors of the label and panel.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseEntered
		// TODO add your handling code here:
		jLabel6.setForeground(jPanel4.getBackground());
		jPanel4.setBackground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel6MouseEntered

	/**
	 * This method is called when the user moves the mouse out of the "disconnect"
	 * label.
	 * It changes the foreground and background colors of the label and panel.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseExited
		// TODO add your handling code here:
		jPanel4.setBackground(jLabel6.getForeground());
		jLabel6.setForeground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel6MouseExited

	/**
	 * This method is called when the user clicks on the jTextField1 text field.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField1MouseClicked
		// TODO add your handling code here:

	}// GEN-LAST:event_jTextField1MouseClicked

	/**
	 * This method is called when the jTextField1 text field gains focus.
	 * It sets the text to an empty string.
	 * 
	 * @param evt the FocusEvent that triggered the method
	 */
	private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField1FocusGained
		// TODO add your handling code here:
		jTextField1.setText("");
	}// GEN-LAST:event_jTextField1FocusGained

	/**
	 * This method is called when the jTextField1 text field loses focus.
	 * It sets the text to "Type your message here...".
	 * 
	 * @param evt the FocusEvent that triggered the method
	 */
	private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField1FocusLost
		// TODO add your handling code here:
		jTextField1.setText("Type your message here...");
	}// GEN-LAST:event_jTextField1FocusLost

	/**
	 * This method is called when the user clicks on the "send message" label.
	 * It sends a message packet to the server with the contents of the jTextField1
	 * text field.
	 * If the message starts with the "/call" command, it sends a call packet
	 * instead.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MouseClicked
		String s = jTextField1.getText();
		Packet packet;

		// check for call command
		if (s.length() > 8) {
			if (s.substring(0, 9).equals("/calllist")) {
				// request the call list from server
				packet = new Packet("calllist", false, sessionId, null);
			} else {
				packet = new Packet("message", username, sessionId, s, true);
			}
		} else if (s.length() > 4) {

			if (s.substring(0, 5).equals("/call")) {

				int channel = Integer.parseInt(s.substring(6, 7));

				// join or leave the call
				packet = new Packet("call", sessionId, inCall, true, 0, new ArrayList<InetAddress>(), channel);
				inCall = !inCall;
			} else {
				packet = new Packet("message", username, sessionId, s, true);
			}
		} else {
			packet = new Packet("message", username, sessionId, s, true);
		}

		try {
			out.writeObject(packet);
		} catch (IOException e) {
			e.printStackTrace();
		}
		jTextField1.setText("");
	}// GEN-LAST:event_jLabel4MouseClicked

	/**
	 * Handles opening the voice note frame.
	 * 
	 * @param evt the MouseEvent that triggered the method
	 */
	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseClicked
		// Create voice note frame
		VoiceNote voiceNoteFrame = new VoiceNote(sessionId, username, out, true, vnReceived);
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				voiceNoteFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
				voiceNoteFrame.setVisible(true);
			}
		});
	} // GEN-LAST:event_jLabel5MouseClicked

	/**
	 * Scales an image to fit inside a given JLabel
	 * 
	 * @param j     The JLabel to set the scaled image on
	 * @param image The path of the image to scale
	 */
	public void scaleImage(JLabel j, String image) {
		ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(image)));

		Image img1 = myImage.getImage();
		Image img2 = img1.getScaledInstance(j.getWidth() - 10, j.getHeight() - 10, Image.SCALE_SMOOTH);
		ImageIcon i = new ImageIcon(img2);
		j.setIcon(i);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PrivateSession.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PrivateSession.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PrivateSession.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PrivateSession.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		// java.awt.EventQueue.invokeLater(new Runnable() {
		// public void run() {
		// new PrivateSession().setVisible(true);
		// }
		// });
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	public javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
