
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.concurrent.ExecutionException;

import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.TargetDataLine;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class VoiceNote extends javax.swing.JFrame {

	Integer sessionId;
	String from;
	ObjectOutputStream outSocket;
	boolean isPrivate;

	String selectedVn;
	TargetDataLine tDataLine;

	Thread recordingThread = new Thread();

	/**
	 * Creates new form VoiceNote
	 */
	public VoiceNote(Integer sessionId, String from, ObjectOutputStream outSocket, boolean isPrivate,
			ArrayList<String> vnReceived) {
		this.sessionId = sessionId;
		this.from = from;
		this.outSocket = outSocket;
		this.isPrivate = isPrivate;
		initComponents();
		scaleImage(jLabel1, "images/voicenoteIdle.png");

		// set received voice notes
		jList1.setListData(Arrays.copyOf(vnReceived.toArray(), vnReceived.size(), String[].class));

		try {
			// Create audio format and line for overwrite errors
			AudioFormat audioFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 44100, 16, 2, 4, 44100,
					false);
			DataLine.Info dInfo = new DataLine.Info(TargetDataLine.class, audioFormat);

			tDataLine = (TargetDataLine) AudioSystem.getLine(dInfo);

		} catch (Exception err) {
			err.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel9 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList<>();
		jPanel6 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel9.setBackground(new java.awt.Color(33, 36, 43));

		jPanel7.setBackground(new java.awt.Color(45, 49, 58));

		jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setText("VoiceNote");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel7,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));
		jPanel7Layout.setVerticalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel7,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										46, Short.MAX_VALUE)
								.addContainerGap()));

		jPanel2.setBackground(new java.awt.Color(45, 49, 58));

		jPanel1.setBackground(new java.awt.Color(33, 36, 43));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 76, 223), 5));

		jLabel8.setBackground(new java.awt.Color(33, 36, 43));
		jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(137, 76, 223));
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel8.setText("Start recording");
		jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel8MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel8MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel8MouseExited(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel8,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										205, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel8,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										34, Short.MAX_VALUE)
								.addContainerGap()));

		jLabel1.setText("jLabel1");

		jPanel8.setBackground(new java.awt.Color(137, 76, 223));
		jPanel8.setForeground(new java.awt.Color(137, 76, 223));

		jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("Receive");
		jLabel4.setToolTipText("");

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel4,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));
		jPanel8Layout.setVerticalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel4,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel2Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel2Layout.createSequentialGroup()
														.addGap(0, 0, Short.MAX_VALUE)
														.addComponent(jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																141,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(46, 46, 46))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel2Layout.createSequentialGroup()
														.addComponent(jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addContainerGap())))
						.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
								.createSequentialGroup()
								.addComponent(jPanel8,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGap(51, 51, 51)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										137,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(47, 47, 47)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(45, 49, 58));

		jPanel4.setBackground(new java.awt.Color(33, 36, 43));
		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 76, 223), 5));

		jLabel9.setBackground(new java.awt.Color(33, 36, 43));
		jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(137, 76, 223));
		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel9.setText("Play voicenote");
		jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel9MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel9MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel9MouseExited(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel9,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										211, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel9,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										34, Short.MAX_VALUE)
								.addContainerGap()));

		jScrollPane1.setBorder(null);

		jList1.setBackground(new java.awt.Color(45, 49, 58));
		jList1.setBorder(null);
		jList1.setForeground(new java.awt.Color(255, 255, 255));
		jList1.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jList1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jList1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jList1);

		jPanel6.setBackground(new java.awt.Color(137, 76, 223));
		jPanel6.setForeground(new java.awt.Color(137, 76, 223));

		jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("Receive");
		jLabel3.setToolTipText("");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel3Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1)
										.addComponent(jPanel4,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addContainerGap())
						.addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
								.createSequentialGroup()
								.addComponent(jPanel6,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										211,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGap(18, 18, 18)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25)));
		jPanel9Layout.setVerticalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addComponent(jPanel7,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(jPanel9Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING,
										false)
										.addComponent(jPanel3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jPanel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addContainerGap(17, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel9,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel9,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// set selected vn filename
	private void jList1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jList1MouseClicked
		selectedVn = (String) jList1.getModel().getElementAt(jList1.locationToIndex(evt.getPoint()));

	}// GEN-LAST:event_jList1MouseClicked

	private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseEntered
		// TODO add your handling code here:
		jLabel9.setForeground(jPanel4.getBackground());
		jPanel4.setBackground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel9MouseEntered

	// play selected voice note
	private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseClicked
		try {

			File vnFile = new File("voicenotes_receive/" + selectedVn);
			AudioInputStream audioIn = AudioSystem.getAudioInputStream(vnFile);
			Clip clip = AudioSystem.getClip();

			clip.open(audioIn);
			clip.start();

		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("TRYING TO PLAY : " + selectedVn);
		}

	}// GEN-LAST:event_jLabel9MouseClicked

	private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseExited
		// TODO add your handling code here:
		jPanel4.setBackground(jLabel9.getForeground());
		jLabel9.setForeground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel9MouseExited

	private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseEntered
		// TODO add your handling code here:
		jLabel8.setForeground(jPanel1.getBackground());
		jPanel1.setBackground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel8MouseEntered

	private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseExited
		// TODO add your handling code here:
		jPanel1.setBackground(jLabel8.getForeground());
		jLabel8.setForeground(new Color(137, 76, 223));
	}// GEN-LAST:event_jLabel8MouseExited

	// record audio
	private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseClicked

		// Create audio format
		AudioFormat audioFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 44100, 16, 2, 4, 44100,
				false);
		DataLine.Info dInfo = new DataLine.Info(TargetDataLine.class, audioFormat);

		// Setup target to record
		try {

			if (jLabel8.getText().equals("Start recording")) {

				tDataLine = (TargetDataLine) AudioSystem.getLine(dInfo);

				// Start recording voice note
				scaleImage(jLabel1, "images/voicenoteActive.png");
				jLabel8.setText("Stop recording");

				// Start recording
				tDataLine.open();
				tDataLine.start();

				// Thread for continuously recording mic
				recordingThread = new Thread(() -> {
					AudioInputStream in = new AudioInputStream(tDataLine);
					File out = new File("voicenotes_send/voicenote.wav");
					// Keep on listing to in and save audio
					try {
						AudioSystem.write(in, AudioFileFormat.Type.WAVE, out);
						System.out.println("done writing");
					} catch (IOException e) {
						e.printStackTrace();
					}
				});

				recordingThread.start();

			} else if (jLabel8.getText().equals("Stop recording")) {
				// Stop recording voice note
				tDataLine.stop();

				// Stop the recording thread and wait for it to finish
				if (recordingThread != null && recordingThread.isAlive()) {
					recordingThread.interrupt();
					try {
						recordingThread.join();
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}

				tDataLine.close();

				jLabel8.setText("Send another");
				scaleImage(jLabel1, "images/voicenoteSent.png");

				try {
					// send the voice note to the session
					FileInputStream vnFile = new FileInputStream("voicenotes_send/voicenote.wav");
					Packet packet = new Packet("voicenote", from, sessionId, vnFile.readAllBytes(),
							isPrivate);
					outSocket.writeObject(packet);
					vnFile.close();
				} catch (Exception err) {
					err.printStackTrace();
				}

			} else {
				jLabel8.setText("Start recording");
				scaleImage(jLabel1, "images/voicenoteIdle.png");
			}
		} catch (LineUnavailableException e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_jLabel8MouseClicked

	public void scaleImage(JLabel j, String image) {
		ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(image)));

		Image img1 = myImage.getImage();
		Image img2 = img1.getScaledInstance(j.getWidth() - 10, j.getHeight() - 10, Image.SCALE_SMOOTH);
		ImageIcon i = new ImageIcon(img2);
		j.setIcon(i);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VoiceNote.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VoiceNote.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VoiceNote.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VoiceNote.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		// java.awt.EventQueue.invokeLater(new Runnable() {
		// public void run() {
		// new VoiceNote().setVisible(true);
		// }
		// });
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JList<String> jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
